### ISSUE TITLE
箇条書きでインデントを下げると元に戻らない

### ISSUE THREAD

**Issue by uhooi** [ios-osushi/website#83]
## 不具合

箇条書きでインデントを下げると、インデントを戻しても下がったままになってしまう。

```markdown
- ソースを壊す変更は含まれていません
- Xcode の最小サポートバージョンが 13.3 に上がりました
- 各プラットフォームの最小サポートバージョンが上がりました
  - iOS: 13.0
  - macOS: 10.15
  - watchOS: 6.0
  - tvOS: 13.0
- Swift Structured Concurrency を採用しました
  - 従来の completion ベースの API と同等のフル機能を備えています
- [NukeUI](https://github.com/kean/NukeUI) がメインリポジトリの一部になりました
- ドキュメントが DocC で書き直され、GitHub へホスティングしました
  - Nuke: [https://kean-docs.github.io/nuke/documentation/nuke/](https://kean-docs.github.io/nuke/documentation/nuke/)
  - NukeUI: [https://kean-docs.github.io/nukeui/documentation/nukeui/](https://kean-docs.github.io/nukeui/documentation/nukeui/)
  - NukeExtensions: [https://kean-docs.github.io/nukeextensions/documentation/nukeextensions/](https://kean-docs.github.io/nukeextensions/documentation/nukeextensions/)
```

↓

|スクリーンショット|
|:--:|
|<img width="749" alt="スクリーンショット 2022-07-23 11 32 10" src="https://user-images.githubusercontent.com/21194714/180587324-03ace007-b0fb-4a83-b5a3-be4bbad2c46a.png">|

## 原因

おそらく私が書いた CSS が悪いと思われる。

```css
.content > ul {
    margin-top: 1.5em;
    margin-bottom: 1.5em;
}

.content ul {
    margin-left: 1.5em;
}

.content li {
    line-height: 1.5em;
}
```

ref: https://github.com/ios-osushi/website/pull/44/commits/7d5deb641e54478d9437b1e02755dbcc1c2819df

**Comment by uhooi** [comment]
CSS でなく HTML に問題があることがわかった。
ref: https://twitter.com/nnabeyang/status/1550681500181762048

**Comment by uhooi** [comment]
Publish を修正しないと、 `ul` がネストしているのを直せない。
CSS で見た目は回避できるので、こちらを適用したい。

```css
.content ul ul {
    margin-left: 0;
}
```

ref: https://twitter.com/murokaco/status/1550683974330380288
